name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.5'  # Adjust your Swift version

      - name: Build and Test
        run: swift test
